In [10]:
import numpy as np 
import pandas as pd 
from sklearn.datasets import load_iris

In [11]:
iris = load_iris() 
x = pd.DataFrame(iris.data, columns=iris.feature_names) 
y = iris.target

In [12]:
#Splitting data
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest, = train_test_split(x,y, test_size=0.3, random_state=42)

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
nb = GaussianNB()
nb.fit(xtrain, ytrain)
ypred = nb.predict(xtest)

In [15]:
#Evaluate
from sklearn.metrics import classification_report, confusion_matrix
cm=confusion_matrix(ytest,ypred)

In [16]:
print("Confusion matrix:\n", cm)

Confusion matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [17]:
print("Classification Report \n", classification_report(ytest, ypred))

Classification Report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [18]:
#Validate on unseen data
newTest =  np.array([[ 4.5, 1.2, 3.1, 2.1 ]])
pred = nb.predict(newTest)
print('predicted unseen data label')
if pred==0:
    print('Setosa')
elif pred==1:
    print('Versicolor')
else:
    print('Verginica')

predicted unseen data label
Versicolor


/home/notarkhit/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
